### ISSUE TITLE
[Docs] Readme.md 문서 수정

### ISSUE THREAD

**Issue by CodingKirby** [CodingKirby/DevCourse-FullStack#5]
## 작업내역

- None

## TODO

- [ ] Readme.md 문서를 최근 내역으로 수정하기
- [ ] 관련 프로젝트 저장소 링크하기

**Comment by CodingKirby** [comment]
### 선행 작업

- [ ] 각 주차 및 파트 별로 Readme.md 문서(WIL, TIL) 추가하기
