### ISSUE TITLE
[Docs] Week 15에 WIL 작성하기

### ISSUE THREAD

**Issue by CodingKirby** [CodingKirby/DevCourse-FullStack#6]
## 작업 내역

- Week15에 Readme.md 생성

## TODO

- [ ] 오픈소스 개념 정리
- [ ] 오픈소스 라이선스 정리
- [ ] 깃허브에 오픈소스 라이선스 추가하는 법 정리
